version: '3.2'

services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - webnet

  silk-api:
    env_file: ./config/.env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    command: python manage.py runserver 0.0.0.0:${SERVER_PORT}
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#    ports:
#      - "${SERVER_PORT}:${SERVER_PORT}"
#    depends_on:
#      - db
#    links:
#      - db:db
    networks:
      - webnet

#  db:
#    container_name: db
#    image: postgres
#    restart: always
#    ports:
#      - "5432:5432"
#    networks:
#      - webnet
#    env_file:
#      - ./.env
#    volumes:
#    - ../database/database/pgdata:/var/lib/postgresql/data

networks:
    webnet:
